# fly.toml app configuration file generated for balansi-staging on 2026-03-13T09:12:59-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'balansi-staging'
primary_region = 'gru'

[env]
  HTTP_PORT = "8079"

[http_service]
  internal_port = 8079
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 1024

[[mounts]]
  destination = "/rails/storage"
  source = "balansi_storage"
