# SimpleCov Configuration
#
# Code coverage is controlled via the COV environment variable:
#   COV=1  - Enable code coverage reporting (shows coverage report, enforces minimum coverage, and shows slow tests > 500ms)
#   COV=0  - Disable code coverage (no coverage report, no warnings, no performance profiling)
#   (unset) - Disable code coverage (default behavior for faster test runs)
#
# Usage:
#   COV=1 bundle exec rspec                    # Run tests with coverage and slow test profiling
#   COV=0 bundle exec rspec                    # Run tests without coverage
#   bundle exec rspec                          # Run tests without coverage (default)
#
# Performance Profiling (only when COV=1):
#   Tests slower than 500ms (0.5 seconds) will be reported at the end of the test run.
#   This helps identify performance bottlenecks without cluttering the output during regular test runs.
#
# SimpleCov must be required before any application code.
# Skip SimpleCov when running via Ruby LSP to avoid conflicts with its built-in coverage.
ruby_lsp_running = ARGV.any? { |arg| arg.include?("ruby_lsp_rspec") || arg.include?("RubyLsp::RSpec") }
coverage_enabled = ENV["COV"] == "1"

if coverage_enabled && !ruby_lsp_running
  require "simplecov"
  begin
    # Start SimpleCov with 'rails' preset for automatic grouping
    # The 'rails' preset automatically filters /config/, /db/, /vendor/bundle/
    # and groups code by Controllers, Models, Helpers, Mailers, Libraries
    SimpleCov.start "rails" do
      # Additional filters
      add_filter "/spec/"
      add_filter "/vendor/"

      # Filter out gem files that Ruby LSP may include (they shouldn't count for coverage)
      add_filter do |source_file|
        source_file.filename.match?(%r{/(\.bundle|\.rbenv|\.asdf|gems)/})
      end

      # Explicit grouping for better coverage reporting
      add_group "Controllers", "app/controllers"
      add_group "Models", "app/models"
      add_group "Services", "app/services"
      add_group "Interactions", "app/interactions"
      add_group "Helpers", "app/helpers"
      add_group "Mailers", "app/mailers"
      add_group "Jobs", "app/jobs"

      minimum_coverage 90

      # Merge multiple test runs (useful if running tests in parallel)
      merge_timeout 3600
    end
  rescue RuntimeError => e
    # If Coverage is already running, skip SimpleCov (tests will still run)
    raise e unless e.message.include?("coverage measurement is already setup")
  end
end

module FixtureBootstrap
  FIXTURE_SET = %w[users patients journals meals exercises].freeze

  def ensure_fixtures_are_loaded
    return if fixtures_ready?

    fixture_path = File.expand_path("fixtures", __dir__)
    ActiveRecord::FixtureSet.reset_cache
    ActiveRecord::FixtureSet.create_fixtures(fixture_path, FIXTURE_SET)
  end

  private

  def fixtures_ready?
    return false unless defined?(User) && defined?(Patient) && defined?(Journal)

    User.exists?(1001) && Patient.exists?(2001) && Journal.exists?(3001)
  end
end

Object.include FixtureBootstrap

# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# See https://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  # rspec-expectations config goes here. You can use an alternate
  # assertion/expectation library such as wrong or the stdlib/minitest
  # assertions if you prefer.
  config.expect_with :rspec do |expectations|
    # This option will default to `true` in RSpec 4. It makes the `description`
    # and `failure_message` of custom matchers include text for helper methods
    # defined using `chain`, e.g.:
    #     be_bigger_than(2).and_smaller_than(4).description
    #     # => "be bigger than 2 and smaller than 4"
    # ...rather than:
    #     # => "be bigger than 2"
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as bogus or mocha) by changing the `mock_with` option here.
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended, and will default to
    # `true` in RSpec 4.
    mocks.verify_partial_doubles = true
  end

  # This option will default to `:apply_to_host_groups` in RSpec 4 (and will
  # have no way to turn it off -- the option exists only for backwards
  # compatibility in RSpec 3). It causes shared context metadata to be
  # inherited by the metadata hash of host groups and examples, rather than
  # triggering implicit auto-inclusion in groups with matching metadata.
  config.shared_context_metadata_behavior = :apply_to_host_groups

  # Focus mode: allows you to limit a spec run to individual examples or groups
  # by tagging them with `:focus` metadata. Use `fit`, `fdescribe`, or `fcontext`
  # as aliases. When nothing is tagged with `:focus`, all examples get run.
  config.filter_run_when_matching :focus

  # Persist example status between runs to support `--only-failures` and `--next-failure` CLI options.
  # This file should be ignored by source control (already in .gitignore).
  config.example_status_persistence_file_path = "spec/examples.txt"

  # Disable monkey patching for cleaner syntax (recommended for new projects).
  # This limits available syntax to non-monkey patched mode.
  # See: https://rspec.info/features/3-12/rspec-core/configuration/zero-monkey-patching-mode/
  config.disable_monkey_patching!

  # Use documentation formatter when running a single spec file for better readability.
  # When running the full suite, use progress formatter (default) for speed.
  if config.files_to_run.one?
    config.default_formatter = "doc"
  end

  # Profile slow tests (over 500ms / 0.5 seconds) to help identify performance bottlenecks.
  # Only enabled when COV=1 to avoid cluttering output during regular test runs.
  # Only tests that exceed the 500ms threshold will be shown in the report.
  if ENV["COV"] == "1"
    require_relative "support/slow_test_formatter"
    SlowTestTracker.initialize

    config.after(:example) do |example|
      next unless example.execution_result
      next if example.execution_result.status == :pending
      next unless example.execution_result.run_time

      execution_time_ms = example.execution_result.run_time * 1000
      next unless execution_time_ms > SlowTestTracker.threshold_ms

      SlowTestTracker.slow_examples << {
        description: example.full_description,
        location: example.location,
        time: execution_time_ms
      }

      # Track slow example groups
      group_key = example.example_group.parent_groups.last&.description || "Unknown"
      SlowTestTracker.slow_example_groups[group_key][:time] += execution_time_ms
      SlowTestTracker.slow_example_groups[group_key][:count] += 1
    end

    config.after(:suite) do
      SlowTestTracker.report_slow_tests
    end
  end

  # Run specs in random order to surface order dependencies.
  # Use `--seed <number>` to reproduce a specific run order for debugging.
  config.order = :random
  Kernel.srand config.seed
end
